name: GitHub Pages redirect page deployment

on:
  workflow_dispatch:

jobs:
  prepare:
    name: Artifact preparing
    runs-on: ubuntu-latest
    steps:
      - name: Source checkout
        uses: actions/checkout@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: github-pages-redirect

  deploy:
    name: Pages deployment
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-step.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: [prepare]
    steps:
      - name: Deployment
        id: deploy-step
        uses: actions/deploy-pages@v4
